// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsfwcfysslyiemzzvwwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZndjZnlzc2x5aWVtenp2d3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzUxNDcsImV4cCI6MjA3NDMxMTE0N30.ATHSN8DQi2h21W1_fcCXwHouy-Q-ynNrSBc8g6dQZn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});